[package]
name = "tree-sitter-tech-diary"
description = "Tech Diary Markdown grammar for tree-sitter"
version = "0.1.0"
authors = ["Miriam Ruiz"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "tech-diary"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/kreikol/tree-sitter-tech-diary-md"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "tree-sitter-tech-diary-md-blocks/src/*",
  "tree-sitter-tech-diary-md-inline/src/*",
  "tree-sitter-tech-diary-md-blocks/grammar.js",
  "tree-sitter-tech-diary-md-inline/grammar.js",
  "tree-sitter-tech-diary-md-blocks/queries/*",
  "tree-sitter-tech-diary-md-inline/queries/*",
  "common/grammar.js",
  "common/html_entities.json",
]

[features]
parser = ["tree-sitter"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"
tree-sitter = { version = "0.24", optional = true }

[dev-dependencies]
tree-sitter = "0.24.3"

[build-dependencies]
cc = "1.1.22"

[[bin]]
name = "benchmark"
path = "bindings/rust/benchmark.rs"
required-features = ["parser"]

[profile.release]
debug = true

[package.metadata.docs.rs]
features = ["parser"]
rustdoc-args = ["--cfg", "docsrs"]
